---
- name: Deploy Nginx Docker Container
  hosts: localhost
  become: true

  tasks:
    - name: Create Docker Network
      docker_network:
        name: sabs_network

    - name: Pull Nginx Docker image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Pull PHP-FPM Docker image
      docker_image:
        name: zhy7ne/8.1-fpm-alpine-z:2.0
        source: pull

    - name: Pull Percona Master Node Docker image
      docker_image:
        name: zhy7ne/pxc_node0:3.0
        source: pull

    - name: Pull Percona Nodes Docker image
      docker_image:
        name: percona/percona-xtradb-cluster:5.7
        source: pull

    - name: Create PHP-FPM containers
      community.docker.docker_container:
        name: "php-fpm{{ item }}"
        image: zhy7ne/8.1-fpm-alpine-z:2.0
        volumes:
          - "/home/justine/configfiles/:/var/www/html/"
          - "/home/justine/configfiles/index{{ item }}.php:/var/www/html/index.php"
        ports:
          - "{{ 9001 + item }}:9000"
        networks:
          - name: sabs_network
      loop: "{{ range(1, 3) | list }}"

    - name: Create server containers
      community.docker.docker_container:
        name: "server{{ item }}"
        image: "nginx:latest"
        volumes:
          - "/home/justine/configfiles/default{{ item }}.conf:/etc/nginx/conf.d/default.conf"
        ports:
          - "809{{ item }}:80"
        networks:
          - name: sabs_network
      loop: "{{ range(1, 3) | list }}"

    - name: Create Load Balancer container
      community.docker.docker_container:
        name: lb
        image: nginx:latest
        volumes:
          - "/home/justine/configfiles/defaultlb.conf:/etc/nginx/conf.d/default.conf"
        ports:
          - "8080:80"
        networks:
          - name: sabs_network

    - name: Create Reverse Proxy container
      community.docker.docker_container:
        name: rp
        image: nginx:latest
        volumes:
          - "/home/justine/configfiles/defaultrp.conf:/etc/nginx/conf.d/default.conf"
        ports:
          - "8070:80"
        networks:
          - name: sabs_network

    - name: Create PXC Bootstrap Node container
      community.docker.docker_container:
        name: pxc_node0
        image: zhy7ne/pxc_node0:3.0
        env: |
          MYSQL_ALLOW_EMPTY_PASSWORD=yes
          MYSQL_ROOT_PASSWORD=password
          MYSQL_DATABASE=mydatabase
          MYSQL_INITDB_SKIP_TZINFO=yes
          XTRABACKUP_PASSWORD=password
          PXC_ENCRYPT_CLUSTER_TRAFFIC=0
        ports:
          - "33060:3306"
        networks:
          - name: sabs_network

    # Uncomment the following tasks after starting the bootstrap node
    # - name: Create PXC Joiner Nodes containers
    #   community.docker.docker_container:
    #     name: "pxc_node{{ item }}"
    #     image: percona/percona-xtradb-cluster:5.7
    #     env: |
    #       MYSQL_ALLOW_EMPTY_PASSWORD=yes
    #       MYSQL_ROOT_PASSWORD=password
    #       MYSQL_INITDB_SKIP_TZINFO=yes
    #       XTRABACKUP_PASSWORD=password
    #       CLUSTER_NAME=terracluster
    #       CLUSTER_JOIN=pxc_node0
    #       name=pxc_node{{ item }}
    #       net=sabs_network
    #       PXC_ENCRYPT_CLUSTER_TRAFFIC=0
    #     ports:
    #       - "{{ 33061 + item }}:3306"
    #     networks:
    #       - name: sabs_network
    #   loop: "{{ range(1, 3) | list }}"
